#!/bin/sh

set -e

SRC="$HOME/src/flutter/engine/src"
FILES="$HOME/src/cscope/cscope-flutter.files"
mkdir -p `dirname $FILES`

find \
  "$SRC/flutter" \
  "$SRC/third_party/dart/runtime" \
  "$SRC/third_party/skia/include" \
  -type f \
  \( -name "*.[cmhsS]" -o \
     -name "*.cc" -o \
     -name "*.cpp" -o \
     -name "*.mm" -o \
     -name "*.java" \) \
     -print \
  > "$FILES"

find \
  "$SRC/third_party/libcxx/include" \
  ! -name "__*" \
  -type f \
  >> "$FILES"

# In $HOME/src/flutter/engine/src, create a symbolic link named cscope.files to
# the output file $FILES, then run cscope -bqk.
